### ISSUE TITLE
BF VER 0.0.03 Runtime error 5 components (cannot import name)

### ISSUE THREAD

**Issue by Omidmr** [mostaphaRoudsari/Butterfly#100]
Hi @mostaphaRoudsari ,
Many thanks for development and release the new version of the Butterfly.

I found some components of current release that have problems.
Only these (5) components have the same error:

![error](https://cloud.githubusercontent.com/assets/11173265/19869261/d9029b86-9fc0-11e6-852a-564d9edd124d.jpg)

Kind Regards,

-Omid

**Comment by mostaphaRoudsari** [comment]
Hi @Omidmr, Thank you for reporting.

This is because I have changed the structure of butterfly and Grasshopper library is now in a separate folder. The older installer doesn't work with the new structure. Can you use [the new installer] to install butterfly 0.0.03? That should solve the problem.

The file will be copied under `C:\Users\%USERNAME%\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts` and in two separate folders.

![image](https://cloud.githubusercontent.com/assets/2915573/19870463/11113db4-9f87-11e6-9e57-b3f1a21e22a3.png)

**Comment by Omidmr** [comment]
@mostaphaRoudsari , Very nice!!
Butterfly (VER 0.0.03) is flying.
![installer](https://cloud.githubusercontent.com/assets/11173265/19871878/20ce9a72-9fcc-11e6-8af2-e021830d00de.PNG)
![very nice](https://cloud.githubusercontent.com/assets/11173265/19871882/2964b180-9fcc-11e6-8111-5e5e31c8a793.PNG)
![vrtt](https://cloud.githubusercontent.com/assets/11173265/19871886/3df831d0-9fcc-11e6-8ad4-c3594a595d51.PNG)

Thank you so much.
Best regards.

-Omid

**Comment by mostaphaRoudsari** [comment]
Great! Thanks for testing.
