### ISSUE TITLE
Visualize Data in ParaView

### ISSUE THREAD

**Issue by MaxMarschall** [mostaphaRoudsari/Butterfly#103]
Hello,

I am new to ParaView, and would like to use it to visualize wind velocities, stream lines, etc. 

Could somebody please explain what the workflow between Butterfly and ParaFoam would be? I assumed that I could import data into ParaFoam from the case folder that Butterfly creates, but so far I have only managed to import the geometry (.stl) of my buildings and refinement layers. 

I have already run the simulation in Butterfly and collected sample points and their corresponding wind vectors and pressures. Do I need to run the simulation again in ParaView?

Any help much appreciated!

Regards,
Max

**Comment by TheodoreGalanos** [comment]
Hi @MaxMarschall,

ParaView can open any OpenFOAM case folder. Since BF creates conforming OF folders you can certainly use paraview to visualize your cases. You should have a .foam file in your folder which is what paraFoam will use, along with the very structure of the case folder, to open your case.

To do that you need to navigate to the folder of your choosing from the OF terminal and run paraFoam. This will use the internal to OF paraview to open the case. You will see a green button "apply" and at the top there is a selection for which time to display, corresponding to the times already simulated in your case. Bare in mind most versions of paraFoam cannot visualize decomposed results (if you were running in parallel) and you would first need to reconstructPar results to visualize them.

Concerning the visualization of already extracted data on an OF mesh I am not really sure. I haven't tried it but I imagine that paraView is able to do that. But I don't see the reason for you to do it. You can easily visualiza that data in Rhino/GH using for example the recolour mesh component. Create a mesh from your points and plug in the values. 

I would suggest reading the manual of paraFoam on how to use, there are also a lot of videos out there showing its capabilities. It is an extremely powerful program and fun to use really.

Please let me know if there is any problem opening the case with the way described above.

**Comment by MaxMarschall** [comment]
Thanks @TheodoreGalanos for your quick answer, but I'm still at a bit of a loss here, maybe because I am inexperienced with OpenFoam.

When you say "OF terminal", do you mean the one that appears when I open start_OF.bat, or is there some other desktop version of OF? How exactly do I navigate to a folder? 

Also, I looked through the case folder and didn't find a .foam file anywhere (see attached).

**Comment by mostaphaRoudsari** [comment]
Hi @MaxMarschall and @TheodoreGalanos,
Butterfly does run the `reconstructPar` once the analysis is over, so you don't need to do so. Errors are warnings about values in input files. I'm not sure if they effect visualizing the results.

**Comment by MaxMarschall** [comment]
Hi @mostaphaRoudsari,
In the ParaView tutorial files, one is able to select variables for display in the properties panel. 
![01help](https://cloud.githubusercontent.com/assets/23235030/20102492/95244372-a5c6-11e6-8889-596f7dd68d76.png)

When I import my file though, there is a field "Cell Arrays" where I can select the variables ("U2, "espilon", etc.), but I can't select any of those from the drop-down menu at the top. There is only "Solid Color", "vtkCompositeIndex" and "vtkBlockColors".
![01mine](https://cloud.githubusercontent.com/assets/23235030/20102504/9ac792f2-a5c6-11e6-9acd-d4fab387282e.png)

I can't seem to visualize any of my data except for geometry. I must be missing something obvious here...?

**Comment by MaxMarschall** [comment]
Solved! All I had to do was convert the .foam to a .vtk using the "foamToVtk" command in OpenFoam, then open that file instead in ParaView.

**Comment by mostaphaRoudsari** [comment]
@MaxMarschall, Make sure that the results are saved in the folder and then try to check it with ParaView. I would try a time other than 0. You should not need to run `foamToVtk` in order to visualize the results in ParaView.

![image](https://cloud.githubusercontent.com/assets/2915573/20123510/93ddefc8-a5ed-11e6-8cf4-a6333ccdeeaa.png)

I also updated butterfly so it does save an empty .foam file in the folder which you can open with ParaView once you create the case.

**Comment by TheodoreGalanos** [comment]
@MaxMarschall Hi Max, Mostapha is right on. You were at 0 time which only contains your mesh. In order to visualize data you will need to navigate to later times. You can do that from the time slider which is located all the way top and in the middle (it's at 0 when you open). You can also add fields that you can visualize on the properties tab. You should not require foamToVTK for the results but you could potentially use it to visualize your probes or other numerical results you might have. I have never tried it but I did use it to visualize particle movement data for Wind Driven Rain simulations so it might work. Ofc, for that kind of data you can do the same in Rhino and Ladybug Tools with no need for any of that.

Hope this helps.

Kind regards,
Theodore.

**Comment by MaxMarschall** [comment]
Thanks, good to know!
