### ISSUE TITLE
Mesh has no refinements

### ISSUE THREAD

**Issue by MaxMarschall** [mostaphaRoudsari/Butterfly#108]
Hi again,

Here is a problem I keep running into, it would be great to get some help!

![mesh](https://cloud.githubusercontent.com/assets/23235030/20219366/62bc0f0e-a829-11e6-8b57-5872a1c299bf.jpg)

The SHM comes out completely regular with no refinements. 

My setup:
> Geometries:
> - My towers - refLevels (1,5)
> - The plot underneath the towers - refLevels (1,7)
> - Surrounding buildings and landscape - refLevels (1,1)
> 
> Refinements:
> - 1 larger refinement box around my towers - level 3
> - 1 refinement box around the bottom floors of the towers - level 7
> 
> Mesh:
> - Cell size 75x75x75m. The smallest cell should therefore be ca. 60x60x60m
> - My wind tunnel is about 2800x4200x1100m
> - globRefineLevel (2,2)

I may have misunderstood some of the parameters...if someone has time it would be super helpful to get some explanations (or resources where I could look it up).

- What exactly do the `refLevels` on the `WallBoundary` component do, why is it a tuple?
- What does `globRefineLevel `do?
- Could it be that I am producing a mesh with more cells than `maxGlobalCells`? I set this to 3.000.000 and assumed it would be enough.

Any help very much appreciated!
Regards,
Max

**Comment by TheodoreGalanos** [comment]
Hi @MaxMarschall 

I am sorry finished work quite late and didn't get a chance to open your definition. I promise I will do it during the weekend.

First I should say that you cell sizes are way too big to capture the geometries you want to capture. I would start at smth like 10m cell size instead of 75 and perhaps a much smaller domain (10 square kilometers seems A LOT).

Second advice is to not put large differences in the surface refinements. If for exampel you want 7 refinement levels then set it at 7/7 and so on.

Now in general your refinement levels are high but this is probably due to the high initial cell size. If you lower your cell size you can consider perhaps 2 and 3 levels of refinment.

The refLevels in the boundaries are the refinement levels on the surface, the tuple is simply (min, max).

Global refinement is simply a setting that allows you to set the refinement levels in all the mesh or in all the surfaces that are not specifically referenced within SHMDict, without naming them one by one. 

For example having it at (2,2) means at minimum everything in the mesh will be refined 2 times.

If I had to guess the problem then I would definitely say it's about maximum cells. As I said it's a big mesh and the refinement levels are quite high. This means that probably the maximum cells are reached somewhere within surface refinement, which means that region refinement doesn't take place. To give you an example, the 7th refinement for a 75m cell is 0.5m! As your experience grows you will learn to read the SHM output in the terminal and see what is happening.

To summarize I would suggest:

- reducing the boundary domain to the default BF values, which are actually international best practices (3x maxHeight for side, Z, and windward extension, 10-15x for leeward). Set the background mesh at around 10m cell size on all directions.

- reducing the refinement levels to smth like 2 and 3 for both surfaces and regions (this can take some trial and error

- Increasing the maximum global cells if required. For this you will need to review your SHM terminal output and see where the simulation stopped. There will be a sentence like "simulation stopped due to reaching maximum cells". You generally want this happening at your shell refinement, and not during surface refinement, if you want your regions to get refined.

Again, stay with it! Meshing is almost its own science, it can take a while.

I'll try and give a better answer after I've opened your case.

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
@MaxMarschall did you try to visualize mesh edges and zoom in? I believe this happens but you don't see it from your view. There is a component that visualizes mesh points. Use that to just get the mesh points for sHM.

You can also use grading to decrease the number of meshes by decreasing the density of the mesh at the end of the tunnel.

**Comment by MaxMarschall** [comment]
Dear @TheodoreGalanos and @mostaphaRoudsari,

Thanks so much for all that advice! It can be pretty frustrating trying out all those parameter combinations without knowing what one is doing ^^ getting some substantiated advice like this helps A LOT.

Cheers and have a good weekend,
Max

**Comment by MaxMarschall** [comment]
Hi again,

I ran a simulation with @TheodoreGalanos 's suggestion and it worked, but only with a mesh size of 20m instead of 10. The smallest cell size therefore was 2.5m (3 refinement levels max), which is still way too course. 

The PC had 4 cores (8 logical processors) and 4GB RAM. I have now moved to a much better PC with 10 cores (20 logical processors) and 64GB RAM.

I increased all my surface refinements by 1 level, increased the maximum cell count to 10 million, and still SHM fails on "Shell refinement level 2" with this message:

`mpirun noticed that process rank 2 with PID 7889 on node default exited on signal 9 (Killed).`

From what I understand this means I'm out of memory? Can that be? I noticed that if only increase some of the geometries' surface refinements it works.

Another thing I've noticed is that doesn't look at all like I'm actually running on different cores. This is the task manager during SHM:
![unbenannt](https://cloud.githubusercontent.com/assets/23235030/20424453/388c28de-ad76-11e6-9c62-84a90d4c50f1.PNG)

Is this normal?

Regards,
Max

**Comment by TheodoreGalanos** [comment]
Hi Max,

The main characteristic related to total cell count is memory. The memory you have should be more than enough to handle 10m cells. I have similar and can run up to 30mil cell models. 

What happens in your case is actually smth quite common in meshing. At each refinement, SHM will essentially split the cells within the refinement region and create new cells. Now what I am assuming happens is that this happens very suddenly and quite forcefully, meaning the meshing jumps from a number below 10mil cells (which is you cut off for SHM) to a number above 30mil cells (which will make your computer crush). Make it a habit to look at the SHM output. Check the number of cells at shell refinement 1 level and check the same number at level 2 (before your computer crushed).

What you can do to fix this is to reduce the size of your refinement region, it seems like at the moment it is too big, generating too many cells.

Concerning the wind velocity at 1.5m, you can still see that as paraFoam or even probes will interpolate from the nearest cell centre. But if pedestrian wind is what you are interested in I would suggest giving more cells on the Z direction. The best practice is to have 4 cells in the first 2 meters, so that your 1.5m falls in the centre of the 4th cell. To do that you can use the blockMesh gradient inputs of BF. I suggest you search for grading in cfd-online, a lot of articles there. Also, this amazing calculator let's you calculate the ratios: https://openfoamwiki.net/index.php/Scripts/blockMesh_grading_calculation

Good luck!

Kind regards,
Theodore.

**Comment by MaxMarschall** [comment]
Hi @TheodoreGalanos,

I've been doing some parameter studies where I watched the cell count. The failed simulations usually looks something like this:

> Surface Refinement 0: 241118
> Surface Refinement 1: 275012
> Surface Refinement 2: 350381
> Surface Refinement 3: 637675

The converged ones:

> Surface Refinement 0: 241118
> Surface Refinement 1: 275012
> Surface Refinement 2: 350381
> Surface Refinement 3: 637675
> Surface Refinement 4: 645879
> Surface Refinement 5: 646180
> Shell Refinement 0:     716738
> Shell Refinement 1:     870241
> Shell Refinement 2:     882260
> Shell Refinement 3:     882372

It' almost like the cutoff is 1M cells. I've noticed that while I have the maxGlobalCells set to a much higher number, the maxLocalCells is set to 1M in the snappyHexMeshDict....could this bwe the limiting factor, and if so is that parameter exposed in Butterfly?

Cheers,
Max

**Comment by MaxMarschall** [comment]
Ok so maxLocalCells is the maximum number of cells per processor during refinement.
Which seems to be a problem since apparently parallel computation isn't working, despite the fast that I set the numOfCPUs to 20 in Butterfly:
![unbenannt](https://cloud.githubusercontent.com/assets/23235030/20431321/af21d534-ad99-11e6-94bf-24f6c01a03dd.PNG)

Do you have an idea why this is so? Does it have anything to do with Butterfly?

BTW, when I first installed OpenFoam on this PC it didn't work at first - "VT-x" had to be enabled in the BIOS first. When I asked a colleague from our IT department about the simulation only running on 1 processor, he told me that VT-x causes PRECISELY this behaviour: prevent the computer to work in parallel...this can't be true right?

Cheers,
Max

**Comment by TheodoreGalanos** [comment]
Hi Max,

Yes maxLocalCells are the cells per processor. However I don't think they would limit your number of cells, at least I've never have it happen. 

There is a chance that this is normal behaviour in the sense that SHM stops not because the limit on maxLocalCells but simply because it finished refining the mesh (i.e. reached your refinement levels). 
Can you try putting increasing your shell refinement levels and see what happens to the cell count?

If it is indeed an OF / parallel computation issue maybe @mostaphaRoudsari has more input here.

Kind regards,
Theodore.

**Comment by MaxMarschall** [comment]
Hi @TheodoreGalanos and @mostaphaRoudsari ,
First of all thanks for your responsiveness, it is very much appreciated!

If I increase the refinement, the SHM simply stops earlier and produces a regular mesh like the one at the beginning of this thread. The cell count never exceeds 1M. I am almost certain that this is because parallel processing isn't working.

I posted a question on cfd-online about it and they asked which commands I'm using to initiate parallel processing...which ones DO you use? Is that part of your source code exposed anywhere?

Kind regards,
Max

**Comment by MaxMarschall** [comment]
Solved...VirtualBox was somehow deactivated. It's working now!

**Comment by TheodoreGalanos** [comment]
Good to hear @MaxMarschall !

Thanks for adding it here, it can be handy for future reference.

Regards,
Theodore.
