### ISSUE TITLE
2.1 Block mesh

### ISSUE THREAD

**Issue by Suaarch** [mostaphaRoudsari/Butterfly#115]
Hello everyone,
 I'm having this kind of error once I try to define the block mesh step. (I already try to run the file which is typed in the message).
![screenshot 2016-11-21 15 25 23](https://cloud.githubusercontent.com/assets/23550351/20486258/516c72c4-afff-11e6-9bea-b61c72b557af.png) 
Thank you in advance

**Comment by mostaphaRoudsari** [comment]
@Suaarch, This shows that butterfly fails to find the virtual machine. Can you check Oracle VM VirtualBox Manager and make sure `default` is started and running?

![image](https://cloud.githubusercontent.com/assets/2915573/20542296/01d367a6-b0cf-11e6-8247-fc19a68643e7.png)

I'm adding a better description to the error report.

**Comment by Suaarch** [comment]
It's me again....it supposes to work 
![screenshot 2016-11-25 17 32 00](https://cloud.githubusercontent.com/assets/23550351/20631095/2c140256-b335-11e6-84d5-46a1e7cd32c0.png)

**Comment by mostaphaRoudsari** [comment]
Thank you for reporting back.  Let's check step by step.

Script initially tries to find init lines for docker by using `docker-machine env`. You need to go to docker installation folder which should be `C:\Program Files\Docker Toolbox` and then run the command `docker-machine env`.
```cmd
cd "C:\Program Files\Docker Toolbox"
docker-machine env
```
If the machine is not running correctly it will return this error:
```Error checking TLS connection: Host is not running.```
that means OpenFOAM installation has failed or is not running correctly and you need to go back and reinstall OpenFOAM, otherwise it will return something like the lines below:
```
SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://192.168.99.100:2376
SET DOCKER_CERT_PATH=C:\Users\Administrator\.docker\machine\machines\default
SET DOCKER_MACHINE_NAME=default
REM Run this command to configure your shell:
REM     @FOR /f "tokens=*" %i IN ('docker-machine env') DO @%i
```
Run the first 4 lines in command line and then try running `docker ps `. It should return lines below:
```
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS               NAMES
e7a36e8e9eeb        of_v1606plus_centos66_win   "bin/bash /root/.entr"   4 months ago        Up 3 minutes                            of_plus_1606
```
Butterfly looks for `of_plus` and then takes the container id. Let's see what exactly fails on your machine.

**Comment by vansicek** [comment]
Mostapha,

I posted this problem on another issue, but this is exactly where I'm getting an error. The OpenFOAM installation works and the default VM machine runs, but when running "docker ps" the container and image are empty. I'm sure this is the result of the following error when trying to create the OF environment: 

<img width="426" alt="capture" src="https://cloud.githubusercontent.com/assets/6708598/20633514/08aaad42-b30d-11e6-9fd5-fa53f4d2d537.PNG">

I did a little checking on this and it looks like there's an issue with having uppercase letters in your file path to the workingdir. I really don't understand this though, as I would think most would have this problem. Any insight on this? 

And many thanks to you and your team for building and sharing such a great tool.

**Comment by mostaphaRoudsari** [comment]
Hi @vansicek, your issue is different from the one that we have here. I'm almost sure that the issue is because of the white space between Kyle and Vansice in the path. White-space is not allowed in the path, and with the way OpenFOAM for Windows is packaged you can't change the shared folder between the two. Can you change the username and remove the space? You should contact the email that is mentioned in installation instruction for OpenFOAM for Windows and at least let them know about this.

**Comment by mostaphaRoudsari** [comment]
This was an issue by installing OpenFOAM under a different username than the one that's running the analysis. The issue is the the OpenFOAM container will save the results under the username that is used to install the image. Installing OpenFOAM under the same username will solve the issue.
