### ISSUE TITLE
Urban wind flow solution run issues

### ISSUE THREAD

**Issue by saket411** [mostaphaRoudsari/butterfly#147]
I set up an urban model for outdoor wind analysis. I have contour mesh as well but for a first run I have not included it. I remember it gave a memory error upon running blockmesh with the contours.
![image](https://cloud.githubusercontent.com/assets/1322619/21678999/71e28ff2-d37c-11e6-9d1d-4a797221fd6b.png)

I am unable to do the grading properly
![image](https://cloud.githubusercontent.com/assets/1322619/21680692/49f5e322-d386-11e6-8d6a-6c714e100353.png)

which results in this error upon running the solution. 
![image](https://cloud.githubusercontent.com/assets/1322619/21678981/61208a02-d37c-11e6-8da5-851e2d121ba5.png)

I checked a lot and even verified with the script TheodoreGalanos posted in #144 
No luck though. Would be great if someone can have a look, I have attached the script. 
[to share.zip](https://github.com/mostaphaRoudsari/butterfly/files/687247/to.share.zip)

Many Thanks for the help!!

**Comment by TheodoreGalanos** [comment]
I think the size of your cells is quite big, if that is what I see in the mesh picture (2nd one). I would do smth like 2m max around the buildings, maybe 1m cell on the Z direction for the first 10-15 meters and no bigger than 2m again until the max height.

The low memory issue is probably the VM, provided you have a strong enough computer. Try giving more memory from the VM (you need to open, stop the default process, settings, 2nd tab I think, slide it over to increase memory.

I assume the probes are inside the mesh. Usually this warning has to do with the cell size. It's trying to find a cell center near the point but the mesh is too coarse.  I think it should go away if you refine the mesh.

My grading was only on the Z and not complete. I'll post a complete grading, based on your case, tomorrow from my work pc.

Kind regards,
Theodore.

**Comment by saket411** [comment]
I read the VM memory solution in an old post so did not highlight that but thanks for mentioning the solution again. 

I had been searching for a cell size option for quite some time today. After I was unable to find it I posted the issue and came home. Just now read your comment and thought to give it another try on my personal laptop. I opened your script again and saw the input for cell size. 
I suspect the cell size option was hidden somehow on my work pc.
 
![image](https://cloud.githubusercontent.com/assets/1322619/21683247/902285fa-d393-11e6-996a-2006d8e674da.png)

Many thanks for your time!!
Somehow VM is not running on my personal laptop so I will check the mesh tomorrow. It should work I presume.

**Comment by saket411** [comment]
I changed the cell size looks okay now. Also added multi grading. Hopefully it should speed up the computation. 
![image](https://cloud.githubusercontent.com/assets/1322619/21705113/cc447ec0-d3f8-11e6-9aca-f95f9a38dba3.png)


simpleGrading (
	(
		(0.2 0.1 4.0)
		(0.6 0.8 1.0)
		(0.2 0.1 4.0)
	)
	(
		(0.1 0.1 4.0)
		(0.35 0.7 1.0)
		(0.55 0.2 4.0)
	)
	(
		(0.4 0.7 1.0)
		(0.2 0.2 2.0)
		(0.4 0.1 4.0)
	)
	)

**Comment by TheodoreGalanos** [comment]
Hi @saket411 It looks good, great job.

Now let's polish it.

One of the most important things to take care when grading is the jump from one cell to the other at the boundary of the graded region. This jump should be ideally not more than 1.2-1.3, meaning the cell outside  should be at maximum 1.2-1.3 times bigger.

In your picture there is a big jump in all sides. You can correct this by either adding more cells, and then allocating more cells to the sides (https://openfoamwiki.net/index.php/Scripts/blockMesh_grading_calculation) which though goes against the idea of using the same cells to get higher quality in the region of interest.

The ideal way to do it is to increase the cell expansion. You can either calculate this with the calculator ( or you can trial and error. I would try smth like this:

For X:
(
(0.2 0.2 5.0)
(0.6 0.6 1.0)
(0.2 0.2 5.0)
)

For Y:
(
(0.1 0.15 0.25) //notice here you need 0.25 and not 4 in order to get a decreasing cell size 
(0.35 0.6 1.0)
(0.55 0.26 5.0)
)

Ofc these would change if you changed cell number. This part gets much easier with experience. I also highly recommend you use the calculator above to get better values since I'm doing that completely out of my head..

For Z I would really recommend more cells. It's way too few atm. I would try maybe doubling or tripling them. After you have the number of your cells you can follow this guideline (it can change slightly depending on the study):

- First 2 meters = 4 cells (0.5m cell height)
- Next 8 meters = 8 cells (1m cell height)
- From 10m - max building height = maximum 2m cell (use gradient here to not have a big jump)
- From max building height - top = maximum 5m cell (again use gradient)

This can get heavy quick so if you're doing tests you can feel free using 1m cells until like 10m and then expansion ration that gives you 1.2m (first cell after 10meters) to 5m (last cell at top).

Kind regards,
Theodore.

**Comment by saket411** [comment]
Wow many thanks for the crash course. I will have to understand and absorb the information properly. I reduced the cell size to 10 and it just gets stuck esp. if I preview the meshes. I have few general questions -
1. If I have 10 mil cells how much time would it take to run say 100 steps.
2. How much the no. of analysis planes and spacing between the analysis points (probes) influence the run time.
3. If I calculate only velocity and not pressure, does it speeds up my run. Right now its set to calculating both of them.
4. If my analysis plane is only around a buildings pedestrian level lets say... a 20m x 20m plane, should I focus my grading density to be more only around that area or I should fine grad the whole 500m x 500m urban landscape.

**Comment by saket411** [comment]
Thanks for the response. 
I have been trying to get a decent setting for a trial run. So far I have only been able to reduce it to 9M cells and the grid I feel is already on the limit (coarse) for a trial run. Refinement is set to 3.
![image](https://cloud.githubusercontent.com/assets/1322619/21711786/d31ab7fe-d42b-11e6-8576-846131911ecc.png)

I am unable to figure out what I should do to reduce the cell size and still be able to have correct results. Its not for the final submission, just design phase and area to be analysed is small as well... ~50x50 m plane. Would prefer to get results for the whole site as well but that looks like an overkill. 

Machine is intel xenon, windows, 32gb of which I have assigned 16gb to VM, 250ssd, 16gb graphics.

Your comments are highly appreciated.

**Comment by saket411** [comment]
Also which point I should use for the locationInMesh?
Currently I have manually selected a point placed somewhere 
I believe I have not understood how this part works. Most of the times I see this error
![image](https://cloud.githubusercontent.com/assets/1322619/21712218/5836a9dc-d42e-11e6-91ca-0f486b24ecc1.png)

**Comment by mimarilker** [comment]
Hi, @saket411 could you please share the latest version of gh file to be reviewed, its not easy to give instructions from a screenshot.

**Comment by saket411** [comment]
[Outdoor Wind Analysis.zip](https://github.com/ladybug-analysis-tools/butterfly/files/689848/Outdoor.Wind.Analysis.zip)
 
That would be great if someone can have a look at it. 
Some things to note - 
1. The wind tunnel size is reduced since I wanted to decrease the no. of cells. 
2. The geometry is far away from the origin. You might need to scroll out a bit.

Q. - When I double the cell size, no. of cells decreased from 9M to 1M. I was wondering if reducing the expansion factors to half while grading would give the same results. I will make a small test run tomorrow to see the impact on meshing. Also so that I get to know which thing impacts how much.

Thanks a lot for looking into it. I am just trying to do a test run but its taking too much time to run on my system. Somewhere some setting is not correct in the gh file and being a beginner I cannot figure it out. 
Any help is highly appreciated. 

Many Thanks!!!

**Comment by CharlesCollin91** [comment]
@saket411 how you finally manage it ? Do you mind sharing your .GH definition ? I didn't find information much butterfly urban analysis exemples, and I found it pretty complicate to use (for a novice ^^).

**Comment by saket411** [comment]
Hi @CharlesCollin91 
It was quite a while back. The [rules ](https://github.com/ladybug-tools/butterfly/issues/147#issuecomment-270828851)given by @TheodoreGalanos are pretty straightforward.
For calculating the grading I use the [online calculator](https://openfoamwiki.net/index.php/Scripts/blockMesh_grading_calculation). I find it easy to input _total expansion ratio_, _width of start cell_, _width of end cell_ and get the other parameters required to input in butterfly. 

It took me a while to get a hold of the whole process. Needs a bit of practise. If you have any specific geometry pls share iit with us. I can then share the excel calc and the workflow for grading that I use currently.

**Comment by TheodoreGalanos** [comment]
Hi @CharlesCollin91 I just want to add that the new version of Butterfly has a magical component that deals with all this for you. All it requires as an input is a rectangle of your area of interest (eg. a square covering your urban geometry), a cell size within that area (my usual is to start with smth around 2-3m to test, lower down to 1m at final), and a total ratio of first to last cell (should be kept below 1.2, I usually use 1.15). The component will then give you a gradient mesh automatically, which you can also preview in Rhino (a 2d version of it that is).

The calculator @saket411 mentioned is quite nice to check though, it will help you understand what is going on in the mesh.

Let me know what happens when you try that.

Kind regards,
Theodore.

**Comment by CharlesCollin91** [comment]
Thank you @saket411 and @TheodoreGalanos.

In fact yes, the new grading component in grasshopper is really helpfull (I didn't have to go through the whole process.. which is also bad cause I don't understand it fully). Regarding all other analysis I have to manage, I don't have couple years to learn in detail butterfly... which is quite bad cause it seems really interesting !!

I opened a new post on LBforum if you want to give a look. I would really appreciate.
https://discourse.ladybug.tools/t/cfd-urban-analysis/3131

Thank you very much !
Best, 
Charles. C.

**Comment by Zazia** [comment]
hi, @TheodoreGalanos @CharlesCollin91 i`m just wandering if you would tell me where i can get this awesome grading componment or the new version of butterfly? i have been trying for a longg time to search for them but being a non-english-speaker-architect have prehaps been a main obsticle .

**Comment by CharlesCollin91** [comment]
Hi, Zazia, 

What you can do is download last version of butterfly on github [here](https://github.com/ladybug-tools/butterfly) and follow the installation [here](https://discourse.ladybug.tools/t/installation-error-openfoam-windows-10/2366/19?u=charlescollin)

Then to see how it works, simply follow this post https://discourse.ladybug.tools/t/meshparams-missing/3106/4?u=charlescollin to see how it works.

Best,
-CC
