### ISSUE TITLE
Add probes

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Butterfly#23]
This is one of the very useful OpenFOAM functions. Here is an example that should be added to controlDict:

```c++
functions
{
probes
{
// Where to load it from
functionObjectLibs ( "libsampling.so" );

type probes;
name probes; // Name of the directory for probe data
outputControl outputTime; // Write at same frequency as fields
outputInterval 5;
fields (p U); // Fields to be probed
probeLocations
    (
        // (x y z)
        ( 1e-06 0 0.01 )
        ( 0.21 -0.20999 0.01 )
        ( 0.21 0.20999 0.01 )
        ( 0.21 0 0.01 )
    );
}
}
```

**Comment by TheodoreGalanos** [comment]
Hi @mostaphaRoudsari 

Yes this is part of the 'function object' component I was planning to add in the other discussion but haven't yet. I'm thinking of a chameleon component, changing depending what the input given or maybe output is requested.
Ofc, Rhino/GH advantage becomes evident  here again, as we can automatically in most cases create these probe locations. 

Two examples I can think of:

1. The create mesh points component we use in daylight simulations can be used to output the points to the function object component. Since it's points that were inserted, probe function can be automatically selected. Then the user can easily choose his/hers attribute to calculate. E.g. if we want to get the average velocity in a room, we connect the zone from the HB model to the zone mesh/point component, get the points, put them in the function object, select velocity as the variable to calculate, average the results at the end (or in another post-processing component).

2. A very usual calculation in urban wind studies is the calculation of pressure in the openings of buildings. Again this can be easily done in HB. We select the glazing surfaces from our zone/whole model, take the center point of the surface, move it 0.5m away (in the surface normal direction), plug in the points, calculate pressure as before.

You can see the possibilities here.

The question is if we want to automate a few of these standard actions (I believe we should) or let the user create GH scripts for it. I think that it's good to automate a few, since users will create scripts one way or another. In this way we give functionality to users, and save A LOT of time. 

That's all for now, will try and describe a function object of sorts in separate issues as you suggested. Also, I'm going to separate the other discussion for components in separate discusssions soon, sorry!

Cheers!
Theodore.

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos thank you for the input. We can and we will automate both but we need to make sure that we don't make a blockbox. For instance we can add a components that returns probe points from HBZones based on what you mentioned and then we can connect these points next to any other point as probes.

**Comment by mostaphaRoudsari** [comment]
http://www.cfdsupport.com/OpenFOAM-Training-by-CFD-Support/node138.html

**Comment by mostaphaRoudsari** [comment]
Butterfly without visualization would have been so lame! even for a beta release.

![image](https://cloud.githubusercontent.com/assets/2915573/16784480/0399de16-4857-11e6-892a-8154c918bfc2.png)

**Comment by stefan-buildSCI** [comment]
Wow!! That's awesome!!!!

**Comment by TheodoreGalanos** [comment]
That is amazing Mostapha! Is that coming off the probes? If that's the case, it's a very nice workaround to the whole mesh visualization I think!

**Comment by mostaphaRoudsari** [comment]
Thank you both. Yes the results is coming from probes folder. Currently you can only create one set of probes and put all the points in together. You can use Grasshopper to separate them later. Eventually you should  be able to create as many as probes as you want with different names.

**Comment by Kristoffernegendahl** [comment]
I really like the concept of using mesh points as probes it works beautifully.

I assume there is no way to add probes finished simulated foam? Is there any considerations in making a probe interpolation module from existing foam files? Simply be course it seems unesserary to re-simulate if you make small changes in e.g. an analysis plane. For now Paraview is doing the job, but it would be nice to have the control within GH.

**Comment by kostnermo** [comment]
> I assume there is no way to add probes finished simulated foam?

There is actually. The same can be done with a _system/sampleDict_  which does the same as _probes{}_ in _controlDict_. It is a tool for probing after run-time. 
In order to probe different locations one would simply create a new sampleDict and run _sample_.

**Comment by mostaphaRoudsari** [comment]
@Kristoffernegendahl in case you connect the new test points and run the analysis just for one more iteration you should get the results for the new probes. Use _endTime_ to limit the number of iterations.

As @kostnermo mentioned probes is a post-processing feature. In honeybee workflow it is integrated as an optional input for the analysis. Maybe we need a different component to make the process more accessible? If you think that would be helpful please open a new issue and I will take care of it soon.

**Comment by Kristoffernegendahl** [comment]
Hi @kostnermo and @mostaphaRoudsari 

I didn't realize could do this just by running one iteration more. Maybe the exiting probe module could be used with a bool that overrides endTime to only perform that single iteration upon user changes of points. But if probes can be used without running iterations at all I think a separate probe extraction module would be nice to have. @mostaphaRoudsari you mention Honeybee does this, which component are you referring to?

**Comment by mostaphaRoudsari** [comment]
I meant butterfly! Corrected the comment. Too many insects I guess :|
