### ISSUE TITLE
create userobjects

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Butterfly#38]
For each component I need to 
- [x] Add description for component, inputs and outputs. This is easy since I can take them from the code itself.
- [x] Add icons! This will be so much work. For now I will just use colored dots... let's make a :rainbow: 

Categories:

0 :: Create

0. butterfly (install, update)
1. Create BFSurface
2. Create BFTunnel
3. Create Case

1 :: Boundary

1. Inlet
2. Outlet
3. Wall
4. Custom Boundary

2 :: BoundaryCondition

1. calculated
2. fixedValue
3. zeroGradient
4. kqWallFunction
5. epsilonWallFunction
6. nutkWallFunction
7. custom

3 :: Mesh

1. blockMesh
2. snappyHexMesh
3. checkMesh
4. updateFvScheme 

4 :: Solver

1. simpleFoam

5 :: PostProcess

1. loadMesh
2. loadPoints
3. loadProbes

6 :: Etc

1. blockMeshDict
2. snappyHexMeshDict
3. controlDict
4. residualControl
5. probes
6. Wind Tunnel Parameters 
7. purgeCase

**Comment by TheodoreGalanos** [comment]
I think the nomeclature could be "boundaries" for inlet, outlet, etc. and "boundary conditions" instead of fields. Fields would then be what is inside 0 folder (p, U, k, epsilon, etc.)

Also I think we are missing a turbulence model tab and a solver tab. The categories for turbulence models can be: 

**RANS - Steady state - incompressible - no buoyancy/temperature/thermal fluxes**

These are the cases we are targeting currently. Out default is the k-epsilon model, but we can easily allow the user to change that to other models (e.g. kEpsilon, RNGkEpsilon,  Realizable k-epsilon) by simply giving the name of the model and Butterfly editing the turbulenceProperties dictionary. These can be chosen by the user depending on the type of study. In my work, k-epsilon is used for validity and stability, RNGkEpsilon for it's better accuracy in flow separation for both external and internal wind studies (e.g. natural ventilation studies, pedestrian comfort, etc.), while Realizable k-epsilon for studies with adverse pressure gradients or rotating geometries (e.g. fan-assisted NV simulations). K-omega SST is also a good solver. A bit more demanding of mesh quality but very good in most cases and especially where high wind velocities exist.  There's a small difference in boundary conditions with omega instead of epsilon. 

**RANS - transient - incompressible - no buoyancy/temperature/thermal fluxes**

These are essentially the same turbulence models but are now run in transient mode. This would have changes on the type of solver used (e.g. pimpleFoam instead of simpleFoam in controlDict), changes in the fvSolution file, and some other. This can be our second batch of default cases as it makes for an easy transition. 

**RANS - steady state/transient - incompressible - with buoyancy/temperature/thermal fluxes**

This is an addition to the above by allowing thermal fluxes or temperatures to influence the fluid flows. Differences are mainly the additional fluid field (e.g. T file in 0 folder) and the different solver used. The simplest case here is to use the boussinesq approximation which allows for an easy case setup of these models. The difference would only be the new field in 0 folder and the selection of a boussinesq solver (mainly buoyantBoussinesqSimpleFoam and buoyantBoussinesqPimpleFoam for steady-state and transient respectively). The steady-state part of this we can also add quite easily in the next stage.

**LES/DES**

These are much more trickier, we can add them at a later stage. I'm not very experienced in these since they are usually not the most practical models to use, especially for my applications. But hopefully, people with experience can assist here. 

Hope this helps.
Theodore.

**Comment by TheodoreGalanos** [comment]
Also we would need a few more boundary conditions I think. For external studies we would need the ABL type boundary conditions that we used in the example (I guess internal/external is yet another distinction). This can even be a component by itself, with the user inputting a wind velocity, reference height, k, and epsilon, and the component makes the BCs. I am not sure, thinking out loud.

Regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos thank you for the insight. I will rename them based on your suggestions.

Turbulence models will be available once I address #28 .
