### ISSUE TITLE
Parallel meshing, simulation

### ISSUE THREAD

**Issue by Kristoffernegendahl** [mostaphaRoudsari/Butterfly#60]
1# Wish. Parallel meshing and simulation in OpenFOAM

I know parallel simulations and meshing options may be something to consider at a much later stage. However I would like to stress that the benefit of core (and even multiple processor) distribution is incredibly important in practice. 

I tried modifying the VM to take advantage of more cores and ram. But it would not matter before parallel is not activated in the foam setup.

**Comment by TheodoreGalanos** [comment]
Hi @Kristoffernegendahl 

Yes this is indeed crucial for CFD, given the size and time required for the simulations.

Unfortunately I have to admit my sin I am not very experienced with Windows OF, trying to get slowly acquainted. I run most of my studies in Linux currently and this isn't an issue. Ofc, 

Enabling Butterfly to run parallel cases is a very simple matter. It's just that I am not sure if the VM can handle it (due to lack of experience I mentioned before). @mostaphaRoudsari can help us here for sure. If it can handle it then we can add this one quite fast.

I'm finishing a project soon and I'll try to test all this. 

Kind regards,
Theodore.

**Comment by Kristoffernegendahl** [comment]
Hi @TheodoreGalanos 

I will look forward to see the parallel tests. 

Just on a side note when I messed around with the VM (through the Oracle interface) I could by shutting down the default Linux/Foam machine redistribute as many cores I have available in my processor to the VM. Also more ram and other things can quite easily be tweaked and it seamed to store the updated specs upon restarting the VM. This might just be enough to switch on parallelism in Butterfly. 

Best regards
Kristoffer

**Comment by mostaphaRoudsari** [comment]
Hi @Kristoffernegendahl and @TheodoreGalanos, It should be possible. As far as the docker has access to multiple cpus, which is possible to set, then OpenFOAM should run in parallel with no issues.

I'm not sure if we have an example but in case you can share an example with me I will implement this after I address #28.

**Comment by Kristoffernegendahl** [comment]
@mostaphaRoudsari I am looking so much forward to this.

**Comment by TheodoreGalanos** [comment]
@mostaphaRoudsari Implementation of this on the OF/BF side is quite straightforward. Only step added to the process is using a decomposeParDict (default, always the same, placed in system) and an input (for that dict) for the number of processors to be used. If that option is selected, BF should run decomposePar before SHM) which will automatically split the the case into x number of folders.

The only trick here is to do similar folder manipulations that we are doing with the non-decomposed cases currently when transitioning from snappyHexMesh to running a case.

The way I do it, which is not the only way ofc but it is clean, is the following:

- blockMesh

- decomposePar without the 0 folder (i.e. having the 0 renamed to smth like 0.org).

- snappyHexMesh like normal

- Run the command _reconstructParMesh -latestTime_ which will reconstruct the last SHM mesh in the main folder (this will be named as /2 or /3 depending how many of the SHM stages in our SHM component were true (default /2).

- Cut the polyMesh folder from the reconstructed mesh to the /constant folder of the case, overwriting the previous one.

- Clean up case folder, delete processor folders, reconstructed folder, etc.

- decomposePar

- Run solver

I'm sure these steps might seem silly at points, so please suggest improvements. In fact, in most of its tutorials OF follows a different approach where the decomposed case is not reconstructed and decomposed again like in my workflow. This is much easier only that it's dirtier for my style (leaving SHM folders in with solution folders). But it's definitely workable and maybe more sensible use of resources.

***
A few notes here. All the commands above should be adapted like the following in order to be run in parallel:

snappyHexMesh -> mpirun -np X snappyHexMesh -parallel

where mpirun is the parallel library (at least in linux), X is the number of processors the user selected.

Additionally, previewing results is a bit harder when the case is decomposed. It is not possible with the parafoam edition that comes with OF although it is possible with the newest editions. However, our probe approach should still work just fine.

That's all I have for now. I think this is simpler than it looks just need to settle on the folder manipulation we choose.

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
Just tested the command and there is no limitation for using parallel runs. @TheodoreGalanos I think this is one the cases that we can do it much faster together.  I won't have time to work on this until Thursday.

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos after our discussion I did check a couple of different workflows. I think the best approach is to separate snappyHexMesh process from solvers. Here is what I'm thinking to implement to butterfly.

```c++
decomposePar -decomposeParDict <meshingDecomposeParDict>
// run snappyHexMesh
mpirun -np <number of processors> snappyHexMesh -parallel -overwrite
// reconstrcut mesh
reconstructParMesh -constant
// remove process folders
rm -r proc*

decomposePar -decomposeParDict <decomposeParDict>
// run the command
mpirun -np <number of processors> <command> -parallel -overwrite
// reconstrcut latest time results
reconstructPar -latestTime
// remove process folders
rm -r proc*
```

**Comment by mostaphaRoudsari** [comment]
@Kristoffernegendahl I just pushed the new butterfly which supports parallel run both for snappyHexMesh and the solution itself. Update butterfly and download the updated example files.

On my laptop, it only makes the solution slower but I don't have enough CPUs on my laptop to dedicate CPUs to VM.  Can you give it a try and let me know the results. There are [a number of changes that I already want to make](https://github.com/mostaphaRoudsari/Butterfly/commit/a6f64b2fad00c0b70fe6fce9d6cb81d334c0569a) but let me know if you have any other inputs.

![image](https://cloud.githubusercontent.com/assets/2915573/18966633/f32c3d3a-864f-11e6-9cb5-ecf4de553dfb.png)

![image](https://cloud.githubusercontent.com/assets/2915573/18966652/0aaad99e-8650-11e6-8067-06a7bb0741c2.png)


@TheodoreGalanos thanks for your help to get this working.

**Comment by Kristoffernegendahl** [comment]
Fantastic. I will have a go with it tomorrow and let you know how it turns out.

**Comment by Kristoffernegendahl** [comment]
Multi core support changes everything. @mostaphaRoudsari and @TheodoreGalanos : this is simply amazing!

<img width="668" alt="grace1" src="https://cloud.githubusercontent.com/assets/3524250/19009427/1faaac5a-8774-11e6-87e9-666ba0a5622c.PNG">

<img width="651" alt="grace2" src="https://cloud.githubusercontent.com/assets/3524250/19009767/5a7fdc30-8777-11e6-8a31-cd8fcfa819ab.PNG">

Next step is to get the VM tuned for maximum performance (ore/cpu distribution) I'll post here when I have tested some setups. 
<img width="281" alt="vm18" src="https://cloud.githubusercontent.com/assets/3524250/19009770/62e27e64-8777-11e6-98cf-19b1931d4438.PNG">

**Comment by mostaphaRoudsari** [comment]
:tada: :balloon: :balloon: Very nice! Thank you @Kristoffernegendahl for testing. I'm going to close this issue, but please feel free to add your findings. I will add a link to this discussion in getting started page.

**Comment by TheodoreGalanos** [comment]
@Kristoffernegendahl Thank you so much for testing! That's awsome!

I was wondering if you can test the `-bind-to-core` and `-bysocket` commands for me in terms of runtime impact. I have been using them in Linux with good effects, wondering how they work under VM. Make sure to not run more cores than you actually have (hyperthreading type of thing) or the commands spit out an error.

Again, thanks! Good job on the screenshots as well, looks like a nice simulation!

Kind regards,
Theodore.

**Comment by Kristoffernegendahl** [comment]
@TheodoreGalanos No problem.

Yes let me test out some possible enhancements. 
I can try to modify the runmanager. You are referring to the actual simulation stage, not the hexMesh right?

Alternatively if you have a test case set up already then you can send it to me:
krne (AT) big.dk

Best regards
Kristoffer

**Comment by mostaphaRoudsari** [comment]
@Kristoffernegendahl you only need to change [this line] (https://github.com/mostaphaRoudsari/Butterfly/blob/85039d9388a57fa630d42d5561cd680e88ec6606/butterfly/runmanager.py#L188) in `runmanager.py`.

It's currently:
```python
cmdList = ('decomposePar', 'mpirun -np %s %s' % (n, cmd),
```
which should be changed to:
```python
cmdList = ('decomposePar', 'mpirun -np %s -bind-to-core -bysocket %s' % (n, cmd),
```
