### ISSUE TITLE
Read/Write OpenFOAM dictionaries to/from python dictionaries

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Butterfly#68]
Currently, I'm using json library to generate c++ like dictionaries and there is no method to read the dictionaries.

pyFOAM has a parser for OpenFOAM dictionaries. I should just use pyFOAM for this. I assume [this file](https://github.com/Unofficial-Extend-Project-Mirror/openfoam-extend-Breeder-other-scripting-PyFoam/blob/master/PyFoam/RunDictionary/ParsedParameterFile.py) is a good place to start and find related methods and classes. @bgschaid is that the right file to start?

[This presentation](http://openfoamwiki.net/images/d/de/HappyFoamingWithPyFoam.pdf) is very helpful to understand the structure of the code.

**Comment by bgschaid** [comment]
Yep. ParsedParameterFile is the class that TRIES to read all the OpenFOAM-files. Emphasis on tries because there are places where only the C++-code knows what it means but PyFoam has to guess. For instance: is (0 5 3) a list with 3 labels or is it a vector?
The class is used all over the place in PyFoam but to get a feel on how it is used have a look at the corresponding unit-tests in the folder unittest

**Comment by mostaphaRoudsari** [comment]
@bgschaid thanks! Will check the unit-test files soon.
