### ISSUE TITLE
Provide links to educational references in Wiki

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Butterfly#81]
Started by @bitacovir [here](https://github.com/mostaphaRoudsari/Butterfly/issues/72#issuecomment-251015195)

@mostaphaRoudsari @TheodoreGalanos! Thanks for the attention on my suggestion. I do not know if you are aware, but with this app you are bringing an engineering tool (OpenFOAM) to the designers and architects scope and workflow. You are pushing some of the hardest barriers for people who does not have this kind of background. In this sense, it is necessary to find or establish a "shared knowledge" from where you can develop your application for multiple users. Thus, it would be good to avoid the use of acronyms and to try to use common language for description of terms. In addition, I think it would be great to include in the wiki a introductory chapter about basic concepts of aerodynamics.
Regards

---
@bitacovir I totally agree with your comments about establishing "shared knowledge" or as I usually put it "shared language". What we have been trying to do so far, mainly in Honeybee, is to educate the users gradually by including both. Using common language is great to get people started and acronyms and technical terms are essential for finding references and reading more about the topic. An introductory chapter about basic concepts of aerodynamics will be very helpful. I think we need a similar link for introduction to OpenFOAM. I can think of a couple that I have seen online but they are all engineering references. Do you know of a good online reference for designers that doesn't oversimplify the topic?

**Comment by bitacovir** [comment]
Shape and Flow: The Essence of Architectural Aerodynamics
https://flexiblemodeling2016.files.wordpress.com/2016/03/shape-and-flow_the-essence-of-architectural-aerodynamics.pdf

Introduction to Environmental Aerodynamics
https://flexiblemodeling2016.files.wordpress.com/2016/03/introduction-aerodynamic-enviroment.pdf

Discomfort Due to Wind Near Buildings
https://flexiblemodeling2016.files.wordpress.com/2016/03/j-gandemer_discomfort-due-to-wind-near-buildings.pdf

Pedestrian wind environment around buildings
https://flexiblemodeling2016.files.wordpress.com/2016/03/pedestrian-wind-environment-around-buildings.pdf

**Comment by mostaphaRoudsari** [comment]
Thank you @bitacovir for adding the resources. I will add them to the wiki.

OpenFOAM for beginners by Jibran Haider
http://jibranhaider.weebly.com/openfoam.html

**Comment by mostaphaRoudsari** [comment]
Added these links and a couple of more to [wiki](https://github.com/mostaphaRoudsari/Butterfly/wiki) under (Learning Resources)[https://github.com/mostaphaRoudsari/Butterfly/wiki/Learning_Resources].
